SERVER-36152 Update requirements.txt

diff --git a/etc/evergreen.yml b/etc/evergreen.yml
--- a/etc/evergreen.yml
+++ b/etc/evergreen.yml
@@ -339,7 +339,6 @@ variables:
   - sharding_op_query_10
   - sharding_op_query_11
   - sharding_op_query_misc
-
 - &unittests
   name: unittests!
   execution_tasks:
@@ -391,9 +390,6 @@ variables:
   setup_group:
   - func: "kill processes"
   - func: "cleanup environment"
-  # The python virtual environment is installed in ${workdir}, which is created in
-  # "set up virtualenv".
-  - func: "set up virtualenv"
   - func: "set task expansion macros"
   - func: "clear OOM messages"
   - command: manifest.load
@@ -441,7 +437,6 @@ variables:
     # We invoke SCons using --jobs = (# of CPUs / 4) to avoid causing out of memory errors due to
     # spawning a large number of linker processes.
     num_scons_link_jobs_available: $(( $(grep -c ^processor /proc/cpuinfo) / 4 ))
-    python: python
     num_jobs_available: $(grep -c ^processor /proc/cpuinfo)
     ext: zip
     use_scons_cache: true
@@ -1272,27 +1267,6 @@ functions:
   - *set_up_credentials
   - *fetch_benchrun_embedded_files
 
-  "set up virtualenv" :
-    command: shell.exec
-    type: test
-    params:
-        script: |
-          # exit immediately if virtualenv is not found
-          set -o errexit
-          set -o verbose
-
-          python_loc=$(which ${python|/opt/mongodbtoolchain/v2/bin/python2})
-          python3_loc=$(which ${python|/opt/mongodbtoolchain/v2/bin/python3})
-          virtualenv_loc=$(which ${virtualenv|virtualenv})
-          if [ "Windows_NT" = "$OS" ]; then
-            python_loc=$(cygpath -w $python_loc)
-            python3_loc=$(cygpath -w c:/python/Python36/python.exe)
-          fi
-          # Set up virtualenv in ${workdir}
-          "$virtualenv_loc" --python "$python_loc" --system-site-packages "${workdir}/venv"
-          # Add virtualenv for python3 in ${workdir}
-          "$virtualenv_loc" --python "$python3_loc" --system-site-packages "${workdir}/venv_3"
-
   "run tests" :
     - *determine_task_timeout
     - *update_task_timeout_expansions
@@ -1320,8 +1294,7 @@ functions:
 
           # activate the virtualenv if it has been set up
           ${activate_virtualenv}
-          pip install boto3==1.5.27
-          pip install mock==2.0.0
+          python2 -mpip install -r ./etc/pip/evgtest-requirements.txt
 
           # Set the TMPDIR environment variable to be a directory in the task's working
           # directory so that temporary files created by processes spawned by resmoke.py get
@@ -1503,11 +1476,13 @@ functions:
 
         ${activate_virtualenv}
         set +o errexit
-        ${compile_env|} $python ./buildscripts/scons.py ${compile_flags|} ${task_compile_flags|} ${scons_cache_args|} $extra_args ${targets} ${additional_targets|} MONGO_VERSION=${version}
+
+        python2 -mpip install -r ./etc/pip/compile-requirements.txt
+        ${compile_env|} python2 ./buildscripts/scons.py ${compile_flags|} ${task_compile_flags|} ${scons_cache_args|} $extra_args ${targets} ${additional_targets|} MONGO_VERSION=${version}
         exit_status=$?
         # If compile fails we do not run any tests
-        if [ $exit_status -ne 0 ]; then
-          if [ ${dump_scons_config_on_failure} = 'true' ]; then
+        if [[ $exit_status -ne 0 ]]; then
+          if [[ "${dump_scons_config_on_failure}" == true ]]; then
             echo "Dumping build/scons/config.log"
             cat build/scons/config.log
           fi
@@ -1907,7 +1882,7 @@ functions:
 
         ${activate_virtualenv}
         # The Windows build variants are running python 2.7.3 and require TLS 1.2 from pyOpenSSL
-        pip install 'pyOpenSSL ; sys_platform == "win32" or sys_platform == "cygwin"'
+        python2 -mpip install 'pyOpenSSL ; sys_platform == "win32" or sys_platform == "cygwin"'
 
         rm -rf /data/install /data/multiversion
         $python buildscripts/setup_multiversion_mongodb.py   \
@@ -2110,8 +2085,7 @@ functions:
 
           set -o errexit
           ${activate_virtualenv}
-          pip install -r buildscripts/requirements.txt
-          pip install -r pytests/requirements.txt
+          python2 -mpip install -r etc/pip/powercycle-requirements.txt
 
           if [ ! -z "${subnet_id}" ]; then
             subnet_id="-n ${subnet_id}"
@@ -2269,7 +2243,7 @@ functions:
           cmds="$cmds; virtualenv --python \$python_loc --system-site-packages ${virtualenv_dir|venv}"
           cmds="$cmds; activate=\$(find ${virtualenv_dir|venv} -name 'activate')"
           cmds="$cmds; . \$activate"
-          cmds="$cmds; pip install -r \$remote_dir/pytests/requirements.txt"
+          cmds="$cmds; pip install -r \$remote_dir/etc/pip/powercycle-requirements.txt"
           ssh_connection_options="${ssh_identity} ${ssh_connection_options}"
           ${activate_virtualenv}
           $python buildscripts/remote_operations.py          \
@@ -2653,44 +2627,30 @@ functions:
       updates:
       - key: activate_virtualenv
         value: |
-          # check if virtualenv is set up
-          if [ -d "${workdir}/venv" ]; then
-            if [ "Windows_NT" = "$OS" ]; then
-              # Need to quote the path on Windows to preserve the separator.
-              . "${workdir}/venv/Scripts/activate" 2> /tmp/activate_error.log
-            else
-              . ${workdir}/venv/bin/activate 2> /tmp/activate_error.log
-            fi
-            if [ $? -ne 0 ]; then
-              echo "Failed to activate virtualenv: $(cat /tmp/activate_error.log)"
-            fi
-            python=python
-          else
-            python=${python|/opt/mongodbtoolchain/v2/bin/python2}
-          fi
-          echo "python set to $(which $python)"
-      - key: activate_virtualenv_3
-        value: |
-          # check if virtualenv for python3 is set up
-          if [ -d "${workdir}/venv_3" ]; then
-            if [ "Windows_NT" = "$OS" ]; then
-              # Need to quote the path on Windows to preserve the separator.
-              . "${workdir}/venv_3/Scripts/activate" 2> /tmp/activate_error.log
-            else
-              . ${workdir}/venv_3/bin/activate 2> /tmp/activate_error.log
-            fi
-            if [ $? -ne 0 ]; then
-              echo "Failed to activate virtualenv: $(cat /tmp/activate_error.log)"
-            fi
-            python=python
-          else
-            if [ "Windows_NT" = "$OS" ]; then
-              python=/cygdrive/c/python/Python36/python
-            else
-              python=${python3|/opt/mongodbtoolchain/v2/bin/python3}
+          # Make virtualenv if it isn't already set up
+          export VENV2_DIR=${workdir}/venv
+          export VENV3_DIR=${workdir}/venv_3
+          export VIRTUALENV=${virtualenv|virtualenv}
+          if [[ ! -d $VENV2_DIR ]]; then
+            if ! bash ${workdir}/src/buildscripts/make-paired-virtualenvs.sh 1>/tmp/virtualenv.log 2>&1; then
+                echo "Unable to set up virtualenv: $(cat /tmp/virtualenv.log)"
+                2>&1 echo "No python2 virtualenv available. Failing..."
+                exit 1
             fi
           fi
-          echo "python set to $(which $python)"
+
+          . "$(find "$VENV2_DIR" -iname activate -print -quit)" 2>/tmp/activate_error.log
+          if [[ $? -ne 0 ]]; then
+              echo "Failed to activate virtualenv: $(cat /tmp/activate_error.log)"
+              exit 1
+          fi
+
+          # This variable is unnecessary but scattered about this file.
+          # If you make changes nearby to an instance, please change it to 'python2'
+          python="$(which python2)"
+
+          echo "python[2] set to $python"
+          echo "python3 set to $(which python3)"
       - key: posix_workdir
         value: eval 'if [ "Windows_NT" = "$OS" ]; then echo $(cygpath -u "${workdir}"); else echo ${workdir}; fi'
       # For ssh disable the options GSSAPIAuthentication, CheckHostIP, StrictHostKeyChecking
@@ -3215,9 +3175,6 @@ functions:
 pre:
   - func: "kill processes"
   - func: "cleanup environment"
-  # The python virtual environment is installed in ${workdir}, which is created in
-  # "set up virtualenv".
-  - func: "set up virtualenv"
   - func: "set task expansion macros"
   - func: "clear OOM messages"
 
@@ -3970,19 +3927,46 @@ tasks:
           set -o errexit
           set -o verbose
 
-          ### TODO: Remove python3 when mypy 0.580 is installed in the toolchain.
-          # Since mypy requires python3, we need to activate the venv_3
-          ${activate_virtualenv_3}
-          pip install -r buildscripts/requirements.txt
-          updated_mypy=$(PATH=$PATH:/opt/mongodbtoolchain/v2/bin which mypy)
-          deactivate
-          ###
           ${activate_virtualenv}
-          # TODO: Remove once the linters have been updated on the variants.
-          pip install -r buildscripts/requirements.txt
-          # The linters require the modules be installed.
-          pip install -r pytests/requirements.txt
-          MYPY=$updated_mypy ${compile_env|} $python ./buildscripts/scons.py ${compile_flags|} --stack-size=1024 lint
+          python3 -mpip install -r etc/pip/lint-requirements.txt
+          python2 -mpip install -r etc/pip/lint-requirements.txt
+          export MYPY="$(
+            PATH+=':/opt/mongodbtoolchain/v2/bin'
+            PATH+=':./venv_3/bin'
+            PATH+=':./venv_3/Scripts'
+            which mypy
+          )"
+          ${compile_env|} python2 ./buildscripts/scons.py ${compile_flags|} --stack-size=1024 lint
+
+- name: verify_pip
+  depends_on: []
+  commands:
+  - command: manifest.load
+  - func: "git get project"
+  - command: shell.exec
+    type: test
+    params:
+      working_dir: src
+      script: |
+        set -o errexit
+        set -o verbose
+
+        ${activate_virtualenv}
+        python2 -mpip freeze >requirements.txt.python2.old
+        python3 -mpip freeze >requirements.txt.python3.old
+
+        python2 -mpip install -r etc/pip/toolchain-requirements.txt
+        python3 -mpip install -r etc/pip/toolchain-requirements.txt
+
+        python2 -mpip freeze >requirements.txt.python2.new
+        python3 -mpip freeze >requirements.txt.python3.new
+
+        # Compare the old freezes to the new freezes.
+        # They should be the same if our toolchain reqs were installed.
+        diff -w requirements.txt.python2.old requirements.txt.python2.new ||
+            1>&2 echo "Allowing out of sync requirements until toolchain upgrades"
+        diff -w requirements.txt.python3.old requirements.txt.python2.new ||
+            1>&2 echo "Allowing out of sync requirements until toolchain upgrades"
 
 - <<: *task_template
   name: burn_in_tests
@@ -4792,16 +4776,6 @@ tasks:
   name: ese
   commands:
   - func: "do setup"
-  - command: shell.exec
-    type: test
-    params:
-      working_dir: src
-      script: |
-        set -o errexit
-        set -o verbose
-
-        ${activate_virtualenv}
-        python -m pip install -r src/mongo/db/modules/enterprise/jstests/encryptdb/libs/requirements.txt
   - func: "run tests"
     vars:
       resmoke_args: --suites=ese --storageEngine=wiredTiger
@@ -6822,9 +6796,7 @@ tasks:
         set -o verbose
 
         ${activate_virtualenv}
-        if [ "Windows_NT" = "$OS" ]; then
-          /cygdrive/c/python/python36/python.exe -m pip install -r buildscripts/requirements.txt
-        fi
+        python3 -m pip install -r etc/pip/core-requirements.txt
   - func: "run tests"
     vars:
       resmoke_args: --suites=free_monitoring --storageEngine=wiredTiger
@@ -7540,8 +7512,7 @@ tasks:
         set -o verbose
 
         ${activate_virtualenv}
-        # Install Python modules to support OAuth with pip until it is available in the toolchain.
-        pip install cryptography==1.7.2 pyjwt==1.5.3
+        python2 -mpip install -r etc/pip/jira-requirements.txt
 
         # We use a small batch size to avoid hitting the load balancer timeout if the Evergreen
         # API query is not fast enough.
@@ -7598,7 +7569,6 @@ task_groups:
     - func: "scons cache pruning"
     - func: "umount shared scons directory"
   setup_task:
-    - func: "set up virtualenv"
     - func: "set task expansion macros"
     - func: "apply compile expansions"
   teardown_task:
@@ -9159,7 +9129,6 @@ buildvariants:
     # We invoke SCons using --jobs = (# of CPUs / 4) to avoid causing out of memory errors due to
     # spawning a large number of linker processes.
     num_scons_link_jobs_available: $(( $(grep -c ^processor /proc/cpuinfo) / 4 ))
-    python: python
     ext: zip
     use_scons_cache: true
     multiversion_platform: windows
@@ -9320,7 +9289,6 @@ buildvariants:
     # We invoke SCons using --jobs = (# of CPUs / 4) to avoid causing out of memory errors due to
     # spawning a large number of linker processes.
     num_scons_link_jobs_available: $(( $(grep -c ^processor /proc/cpuinfo) / 4 ))
-    python: python
     num_jobs_available: $(grep -c ^processor /proc/cpuinfo)
     ext: zip
     use_scons_cache: true
@@ -9341,12 +9309,14 @@ buildvariants:
   - name: compile_TG
     requires:
     - name: burn_in_tests
+    - name: verify_pip
     distros:
     - windows-64-vs2015-large
   - name: compile_benchmarks
     distros:
     - windows-64-vs2015-large
   - name: burn_in_tests
+  - name: verify_pip
   - name: audit
   - name: auth_audit
   - name: benchmarks_orphaned
@@ -9635,7 +9605,6 @@ buildvariants:
     # We invoke SCons using --jobs = (# of CPUs / 4) to avoid causing out of memory errors due to
     # spawning a large number of linker processes.
     num_scons_link_jobs_available: $(( $(grep -c ^processor /proc/cpuinfo) / 4 ))
-    python: python
     num_jobs_available: $(grep -c ^processor /proc/cpuinfo)
     ext: zip
     use_scons_cache: true
@@ -9667,7 +9636,6 @@ buildvariants:
     # We invoke SCons using --jobs = (# of CPUs / 4) to avoid causing out of memory errors due to
     # spawning a large number of linker processes.
     num_scons_link_jobs_available: $(( $(grep -c ^processor /proc/cpuinfo) / 4 ))
-    python: python
     num_jobs_available: $(grep -c ^processor /proc/cpuinfo)
     test_flags: --storageEngine=inMemory --excludeWithAnyTags=requires_persistence,requires_journaling,uses_transactions
     ext: zip
@@ -9741,7 +9709,6 @@ buildvariants:
     # We invoke SCons using --jobs = (# of CPUs / 4) to avoid causing out of memory errors due to
     # spawning a large number of linker processes.
     num_scons_link_jobs_available: $(( $(grep -c ^processor /proc/cpuinfo) / 4 ))
-    python: python
     num_jobs_available: $(grep -c ^processor /proc/cpuinfo)
     ext: zip
     use_scons_cache: true
@@ -9857,7 +9824,6 @@ buildvariants:
     # We invoke SCons using --jobs = (# of CPUs / 4) to avoid causing out of memory errors due to
     # spawning a large number of linker processes.
     num_scons_link_jobs_available: $(( $(grep -c ^processor /proc/cpuinfo) / 4 ))
-    python: python
     num_jobs_available: $(grep -c ^processor /proc/cpuinfo)
     ext: zip
     use_scons_cache: true
@@ -10565,6 +10531,7 @@ buildvariants:
   - name: compile_all_run_unittests_TG
     requires:
     - name: burn_in_tests
+    - name: verify_pip
     - name: lint
     distros:
     - rhel62-large
@@ -10575,6 +10542,7 @@ buildvariants:
   - name: burn_in_tests
     distros:
     - rhel62-large
+  - name: verify_pip
   - name: rollback_fuzzer
   - name: rollback_fuzzer_clean_shutdowns
   - name: rollback_fuzzer_unclean_shutdowns
